# encoding: utf-8

country = Spree::Country.find_or_create_by name:'Chile', iso_name: "CHILE", iso: "CL", iso3: "CHL", numcode: 152, states_required: false

#Chilean states
xi   = Spree::State.find_or_create_by name: 'Aysén del General Carlos Ibanez', abbr: 'AI', country: country
ii   = Spree::State.find_or_create_by name: 'Antofagasta', abbr: 'AN', country: country
ix   = Spree::State.find_or_create_by name: 'Araucanía', abbr: 'AR', country: country
xv   = Spree::State.find_or_create_by name: 'Arica y Parinacota', abbr: 'AP', country: country
iii  = Spree::State.find_or_create_by name: 'Atacama', abbr: 'AT', country: country
viii = Spree::State.find_or_create_by name: 'Bio-Bío', abbr: 'BI', country: country
iv   = Spree::State.find_or_create_by name: 'Coquimbo', abbr: 'CO', country: country
vi   = Spree::State.find_or_create_by name: 'Libertador General Bernardo O\'Higgins', abbr: 'LI', country: country
x    = Spree::State.find_or_create_by name: 'Los Lagos', abbr: 'LL', country: country
xii  = Spree::State.find_or_create_by name: 'Magallanes y de la Antártica Chilena', abbr: 'MA', country: country
vii  = Spree::State.find_or_create_by name: 'Maule', abbr: 'ML', country: country
rm   = Spree::State.find_or_create_by name: 'Metropolitana', abbr: 'RM', country: country
xiv  = Spree::State.find_or_create_by name: 'Los Ríos', abbr: 'LR', country: country
i    = Spree::State.find_or_create_by name: 'Tarapacá', abbr: 'TA', country: country
v    = Spree::State.find_or_create_by name: 'Valparaíso', abbr: 'VS', country: country

Spree::County.find_or_create_by(name: 'Arica',                state: xv)
Spree::County.find_or_create_by(name: 'Camarones',            state: xv)
Spree::County.find_or_create_by(name: 'Putre',                state: xv)
Spree::County.find_or_create_by(name: 'General Lagos',        state: xv)
Spree::County.find_or_create_by(name: 'Iquique',              state: i)
Spree::County.find_or_create_by(name: 'Alto Hospicio',        state: i)
Spree::County.find_or_create_by(name: 'Pozo Almonte',         state: i)
Spree::County.find_or_create_by(name: 'Camiña',               state: i)
Spree::County.find_or_create_by(name: 'Colchane',             state: i)
Spree::County.find_or_create_by(name: 'Huara',                state: i)
Spree::County.find_or_create_by(name: 'Pica',                 state: i)
Spree::County.find_or_create_by(name: 'Antofagasta',          state: ii)
Spree::County.find_or_create_by(name: 'Mejillones',           state: ii)
Spree::County.find_or_create_by(name: 'Sierra Gorda',         state: ii)
Spree::County.find_or_create_by(name: 'Taltal',               state: ii)
Spree::County.find_or_create_by(name: 'Calama',               state: ii)
Spree::County.find_or_create_by(name: 'Ollagüe',              state: ii)
Spree::County.find_or_create_by(name: 'San Pedro de Atacama', state: ii)
Spree::County.find_or_create_by(name: 'Tocopilla',            state: ii)
Spree::County.find_or_create_by(name: 'María Elena',          state: ii)
Spree::County.find_or_create_by(name: 'Copiapó',              state: iii)
Spree::County.find_or_create_by(name: 'Caldera',              state: iii)
Spree::County.find_or_create_by(name: 'Tierra Amarilla',      state: iii)
Spree::County.find_or_create_by(name: 'Chañaral',             state: iii)
Spree::County.find_or_create_by(name: 'Diego de Almagro',     state: iii)
Spree::County.find_or_create_by(name: 'Vallenar',             state: iii)
Spree::County.find_or_create_by(name: 'Alto del Carmen',      state: iii)
Spree::County.find_or_create_by(name: 'Freirina',             state: iii)
Spree::County.find_or_create_by(name: 'Huasco',               state: iii)
Spree::County.find_or_create_by(name: 'La Serena',            state: iv)
Spree::County.find_or_create_by(name: 'Coquimbo',             state: iv)
Spree::County.find_or_create_by(name: 'Andacollo',            state: iv)
Spree::County.find_or_create_by(name: 'La Higuera',           state: iv)
Spree::County.find_or_create_by(name: 'Paiguano',             state: iv)
Spree::County.find_or_create_by(name: 'Vicuña',               state: iv)
Spree::County.find_or_create_by(name: 'Illapel',              state: iv)
Spree::County.find_or_create_by(name: 'Canela',               state: iv)
Spree::County.find_or_create_by(name: 'Los Vilos',            state: iv)
Spree::County.find_or_create_by(name: 'Salamanca',            state: iv)
Spree::County.find_or_create_by(name: 'Ovalle',               state: iv)
Spree::County.find_or_create_by(name: 'Combarbalá',           state: iv)
Spree::County.find_or_create_by(name: 'Monte Patria',         state: iv)
Spree::County.find_or_create_by(name: 'Punitaqui',            state: iv)
Spree::County.find_or_create_by(name: 'Río Hurtado',          state: iv)
Spree::County.find_or_create_by(name: 'Valparaíso',           state: v)
Spree::County.find_or_create_by(name: 'Casablanca',           state: v)
Spree::County.find_or_create_by(name: 'Concón',               state: v)
Spree::County.find_or_create_by(name: 'Juan Fernández',       state: v)
Spree::County.find_or_create_by(name: 'Puchuncaví',           state: v)
Spree::County.find_or_create_by(name: 'Quintero',             state: v)
Spree::County.find_or_create_by(name: 'Viña del Mar',         state: v)
Spree::County.find_or_create_by(name: 'Isla de Pascua',       state: v)
Spree::County.find_or_create_by(name: 'Los Andes',            state: v)
Spree::County.find_or_create_by(name: 'Calle Larga',          state: v)
Spree::County.find_or_create_by(name: 'Rinconada',            state: v)
Spree::County.find_or_create_by(name: 'San Esteban',          state: v)
Spree::County.find_or_create_by(name: 'La Ligua',             state: v)
Spree::County.find_or_create_by(name: 'Cabildo',              state: v)
Spree::County.find_or_create_by(name: 'Papudo',               state: v)
Spree::County.find_or_create_by(name: 'Petorca',              state: v)
Spree::County.find_or_create_by(name: 'Zapallar',             state: v)
Spree::County.find_or_create_by(name: 'Quillota',             state: v)
Spree::County.find_or_create_by(name: 'Calera',               state: v)
Spree::County.find_or_create_by(name: 'Hijuelas',             state: v)
Spree::County.find_or_create_by(name: 'La Cruz',              state: v)
Spree::County.find_or_create_by(name: 'Nogales',              state: v)
Spree::County.find_or_create_by(name: 'San Antonio',          state: v)
Spree::County.find_or_create_by(name: 'Algarrobo',            state: v)
Spree::County.find_or_create_by(name: 'Cartagena',            state: v)
Spree::County.find_or_create_by(name: 'El Quisco',            state: v)
Spree::County.find_or_create_by(name: 'El Tabo',              state: v)
Spree::County.find_or_create_by(name: 'Santo Domingo',        state: v)
Spree::County.find_or_create_by(name: 'San Felipe',           state: v)
Spree::County.find_or_create_by(name: 'Catemu',               state: v)
Spree::County.find_or_create_by(name: 'Llaillay',             state: v)
Spree::County.find_or_create_by(name: 'Panquehue',            state: v)
Spree::County.find_or_create_by(name: 'Putaendo',             state: v)
Spree::County.find_or_create_by(name: 'Santa María',          state: v)
Spree::County.find_or_create_by(name: 'Limache',              state: v)
Spree::County.find_or_create_by(name: 'Quilpué',              state: v)
Spree::County.find_or_create_by(name: 'Villa Alemana',        state: v)
Spree::County.find_or_create_by(name: 'Olmué',                state: v)
Spree::County.find_or_create_by(name: 'Rancagua',             state: vi)
Spree::County.find_or_create_by(name: 'Codegua',              state: vi)
Spree::County.find_or_create_by(name: 'Coinco',               state: vi)
Spree::County.find_or_create_by(name: 'Coltauco',             state: vi)
Spree::County.find_or_create_by(name: 'Doñihue',              state: vi)
Spree::County.find_or_create_by(name: 'Graneros',             state: vi)
Spree::County.find_or_create_by(name: 'Las Cabras',           state: vi)
Spree::County.find_or_create_by(name: 'Machalí',              state: vi)
Spree::County.find_or_create_by(name: 'Malloa',               state: vi)
Spree::County.find_or_create_by(name: 'Mostazal',             state: vi)
Spree::County.find_or_create_by(name: 'Olivar',               state: vi)
Spree::County.find_or_create_by(name: 'Peumo',                state: vi)
Spree::County.find_or_create_by(name: 'Pichidegua',           state: vi)
Spree::County.find_or_create_by(name: 'Quinta de Tilcoco',    state: vi)
Spree::County.find_or_create_by(name: 'Rengo',                state: vi)
Spree::County.find_or_create_by(name: 'Requínoa',             state: vi)
Spree::County.find_or_create_by(name: 'San Vicente',          state: vi)
Spree::County.find_or_create_by(name: 'Pichilemu',            state: vi)
Spree::County.find_or_create_by(name: 'La Estrella',          state: vi)
Spree::County.find_or_create_by(name: 'Litueche',             state: vi)
Spree::County.find_or_create_by(name: 'Marchihue',            state: vi)
Spree::County.find_or_create_by(name: 'Navidad',              state: vi)
Spree::County.find_or_create_by(name: 'Paredones',            state: vi)
Spree::County.find_or_create_by(name: 'San Fernando',         state: vi)
Spree::County.find_or_create_by(name: 'Chépica',              state: vi)
Spree::County.find_or_create_by(name: 'Chimbarongo',          state: vi)
Spree::County.find_or_create_by(name: 'Lolol',                state: vi)
Spree::County.find_or_create_by(name: 'Nancagua',             state: vi)
Spree::County.find_or_create_by(name: 'Palmilla',             state: vi)
Spree::County.find_or_create_by(name: 'Peralillo',            state: vi)
Spree::County.find_or_create_by(name: 'Placilla',             state: vi)
Spree::County.find_or_create_by(name: 'Pumanque',             state: vi)
Spree::County.find_or_create_by(name: 'Santa Cruz',           state: vi)
Spree::County.find_or_create_by(name: 'Talca',                state: vii)
Spree::County.find_or_create_by(name: 'Constitución',         state: vii)
Spree::County.find_or_create_by(name: 'Curepto',              state: vii)
Spree::County.find_or_create_by(name: 'Empedrado',            state: vii)
Spree::County.find_or_create_by(name: 'Maule',                state: vii)
Spree::County.find_or_create_by(name: 'Pelarco',              state: vii)
Spree::County.find_or_create_by(name: 'Pencahue',             state: vii)
Spree::County.find_or_create_by(name: 'Río Claro',            state: vii)
Spree::County.find_or_create_by(name: 'San Clemente',         state: vii)
Spree::County.find_or_create_by(name: 'San Rafael',           state: vii)
Spree::County.find_or_create_by(name: 'Cauquenes',            state: vii)
Spree::County.find_or_create_by(name: 'Chanco',               state: vii)
Spree::County.find_or_create_by(name: 'Pelluhue',             state: vii)
Spree::County.find_or_create_by(name: 'Curicó',               state: vii)
Spree::County.find_or_create_by(name: 'Hualañé',              state: vii)
Spree::County.find_or_create_by(name: 'Licantén',             state: vii)
Spree::County.find_or_create_by(name: 'Molina',               state: vii)
Spree::County.find_or_create_by(name: 'Rauco',                state: vii)
Spree::County.find_or_create_by(name: 'Romeral',              state: vii)
Spree::County.find_or_create_by(name: 'Sagrada Familia',      state: vii)
Spree::County.find_or_create_by(name: 'Teno',                 state: vii)
Spree::County.find_or_create_by(name: 'Vichuquén',            state: vii)
Spree::County.find_or_create_by(name: 'Linares',              state: vii)
Spree::County.find_or_create_by(name: 'Colbún',               state: vii)
Spree::County.find_or_create_by(name: 'Longaví',              state: vii)
Spree::County.find_or_create_by(name: 'Parral',               state: vii)
Spree::County.find_or_create_by(name: 'Retiro',               state: vii)
Spree::County.find_or_create_by(name: 'San Javier',           state: vii)
Spree::County.find_or_create_by(name: 'Villa Alegre',         state: vii)
Spree::County.find_or_create_by(name: 'Yerbas Buenas',        state: vii)
Spree::County.find_or_create_by(name: 'Concepción',           state: viii)
Spree::County.find_or_create_by(name: 'Coronel',              state: viii)
Spree::County.find_or_create_by(name: 'Chiguayante',          state: viii)
Spree::County.find_or_create_by(name: 'Florida',              state: viii)
Spree::County.find_or_create_by(name: 'Hualqui',              state: viii)
Spree::County.find_or_create_by(name: 'Lota',                 state: viii)
Spree::County.find_or_create_by(name: 'Penco',                state: viii)
Spree::County.find_or_create_by(name: 'San Pedro de la Paz',  state: viii)
Spree::County.find_or_create_by(name: 'Santa Juana',          state: viii)
Spree::County.find_or_create_by(name: 'Talcahuano',           state: viii)
Spree::County.find_or_create_by(name: 'Tomé',                 state: viii)
Spree::County.find_or_create_by(name: 'Hualpén',              state: viii)
Spree::County.find_or_create_by(name: 'Lebu',                 state: viii)
Spree::County.find_or_create_by(name: 'Arauco',               state: viii)
Spree::County.find_or_create_by(name: 'Cañete',               state: viii)
Spree::County.find_or_create_by(name: 'Contulmo',             state: viii)
Spree::County.find_or_create_by(name: 'Curanilahue',          state: viii)
Spree::County.find_or_create_by(name: 'Los Alamos',           state: viii)
Spree::County.find_or_create_by(name: 'Tirúa',                state: viii)
Spree::County.find_or_create_by(name: 'Los Angeles',          state: viii)
Spree::County.find_or_create_by(name: 'Antuco',               state: viii)
Spree::County.find_or_create_by(name: 'Cabrero',              state: viii)
Spree::County.find_or_create_by(name: 'Laja',                 state: viii)
Spree::County.find_or_create_by(name: 'Mulchén',              state: viii)
Spree::County.find_or_create_by(name: 'Nacimiento',           state: viii)
Spree::County.find_or_create_by(name: 'Negrete',              state: viii)
Spree::County.find_or_create_by(name: 'Quilaco',              state: viii)
Spree::County.find_or_create_by(name: 'Quilleco',             state: viii)
Spree::County.find_or_create_by(name: 'San Rosendo',          state: viii)
Spree::County.find_or_create_by(name: 'Santa Bárbara',        state: viii)
Spree::County.find_or_create_by(name: 'Tucapel',              state: viii)
Spree::County.find_or_create_by(name: 'Yumbel',               state: viii)
Spree::County.find_or_create_by(name: 'Alto Biobío',          state: viii)
Spree::County.find_or_create_by(name: 'Chillán',              state: viii)
Spree::County.find_or_create_by(name: 'Bulnes',               state: viii)
Spree::County.find_or_create_by(name: 'Cobquecura',           state: viii)
Spree::County.find_or_create_by(name: 'Coelemu',              state: viii)
Spree::County.find_or_create_by(name: 'Coihueco',             state: viii)
Spree::County.find_or_create_by(name: 'Chillán Viejo',        state: viii)
Spree::County.find_or_create_by(name: 'El Carmen',            state: viii)
Spree::County.find_or_create_by(name: 'Ninhue',               state: viii)
Spree::County.find_or_create_by(name: 'Ñiquén',               state: viii)
Spree::County.find_or_create_by(name: 'Pemuco',               state: viii)
Spree::County.find_or_create_by(name: 'Pinto',                state: viii)
Spree::County.find_or_create_by(name: 'Portezuelo',           state: viii)
Spree::County.find_or_create_by(name: 'Quillón',              state: viii)
Spree::County.find_or_create_by(name: 'Quirihue',             state: viii)
Spree::County.find_or_create_by(name: 'Ránquil',              state: viii)
Spree::County.find_or_create_by(name: 'San Carlos',           state: viii)
Spree::County.find_or_create_by(name: 'San Fabián',           state: viii)
Spree::County.find_or_create_by(name: 'San Ignacio',          state: viii)
Spree::County.find_or_create_by(name: 'San Nicolás',          state: viii)
Spree::County.find_or_create_by(name: 'Treguaco',             state: viii)
Spree::County.find_or_create_by(name: 'Yungay',               state: viii)
Spree::County.find_or_create_by(name: 'Temuco',               state: ix)
Spree::County.find_or_create_by(name: 'Carahue',              state: ix)
Spree::County.find_or_create_by(name: 'Cunco',                state: ix)
Spree::County.find_or_create_by(name: 'Curarrehue',           state: ix)
Spree::County.find_or_create_by(name: 'Freire',               state: ix)
Spree::County.find_or_create_by(name: 'Galvarino',            state: ix)
Spree::County.find_or_create_by(name: 'Gorbea',               state: ix)
Spree::County.find_or_create_by(name: 'Lautaro',              state: ix)
Spree::County.find_or_create_by(name: 'Loncoche',             state: ix)
Spree::County.find_or_create_by(name: 'Melipeuco',            state: ix)
Spree::County.find_or_create_by(name: 'Nueva Imperial',       state: ix)
Spree::County.find_or_create_by(name: 'Padre Las Casas',      state: ix)
Spree::County.find_or_create_by(name: 'Perquenco',            state: ix)
Spree::County.find_or_create_by(name: 'Pitrufquén',           state: ix)
Spree::County.find_or_create_by(name: 'Pucón',                state: ix)
Spree::County.find_or_create_by(name: 'Saavedra',             state: ix)
Spree::County.find_or_create_by(name: 'Teodoro Schmidt',      state: ix)
Spree::County.find_or_create_by(name: 'Toltén',               state: ix)
Spree::County.find_or_create_by(name: 'Vilcún',               state: ix)
Spree::County.find_or_create_by(name: 'Villarrica',           state: ix)
Spree::County.find_or_create_by(name: 'Cholchol',             state: ix)
Spree::County.find_or_create_by(name: 'Angol',                state: ix)
Spree::County.find_or_create_by(name: 'Collipulli',           state: ix)
Spree::County.find_or_create_by(name: 'Curacautín',           state: ix)
Spree::County.find_or_create_by(name: 'Ercilla',              state: ix)
Spree::County.find_or_create_by(name: 'Lonquimay',            state: ix)
Spree::County.find_or_create_by(name: 'Los Sauces',           state: ix)
Spree::County.find_or_create_by(name: 'Lumaco',               state: ix)
Spree::County.find_or_create_by(name: 'Purén',                state: ix)
Spree::County.find_or_create_by(name: 'Renaico',              state: ix)
Spree::County.find_or_create_by(name: 'Traiguén',             state: ix)
Spree::County.find_or_create_by(name: 'Victoria',             state: ix)
Spree::County.find_or_create_by(name: 'Valdivia',             state: xiv)
Spree::County.find_or_create_by(name: 'Corral',               state: xiv)
Spree::County.find_or_create_by(name: 'Lanco',                state: xiv)
Spree::County.find_or_create_by(name: 'Los Lagos',            state: xiv)
Spree::County.find_or_create_by(name: 'Máfil',                state: xiv)
Spree::County.find_or_create_by(name: 'Mariquina',            state: xiv)
Spree::County.find_or_create_by(name: 'Paillaco',             state: xiv)
Spree::County.find_or_create_by(name: 'Panguipulli',          state: xiv)
Spree::County.find_or_create_by(name: 'La Unión',             state: xiv)
Spree::County.find_or_create_by(name: 'Futrono',              state: xiv)
Spree::County.find_or_create_by(name: 'Lago Ranco',           state: xiv)
Spree::County.find_or_create_by(name: 'Río Bueno',            state: xiv)
Spree::County.find_or_create_by(name: 'Puerto Montt',         state: x)
Spree::County.find_or_create_by(name: 'Calbuco',              state: x)
Spree::County.find_or_create_by(name: 'Cochamó',              state: x)
Spree::County.find_or_create_by(name: 'Fresia',               state: x)
Spree::County.find_or_create_by(name: 'Frutillar',            state: x)
Spree::County.find_or_create_by(name: 'Los Muermos',          state: x)
Spree::County.find_or_create_by(name: 'Llanquihue',           state: x)
Spree::County.find_or_create_by(name: 'Maullín',              state: x)
Spree::County.find_or_create_by(name: 'Puerto Varas',         state: x)
Spree::County.find_or_create_by(name: 'Castro',               state: x)
Spree::County.find_or_create_by(name: 'Ancud',                state: x)
Spree::County.find_or_create_by(name: 'Chonchi',              state: x)
Spree::County.find_or_create_by(name: 'Curaco de Vélez',      state: x)
Spree::County.find_or_create_by(name: 'Dalcahue',             state: x)
Spree::County.find_or_create_by(name: 'Puqueldón',            state: x)
Spree::County.find_or_create_by(name: 'Queilén',              state: x)
Spree::County.find_or_create_by(name: 'Quellón',              state: x)
Spree::County.find_or_create_by(name: 'Quemchi',              state: x)
Spree::County.find_or_create_by(name: 'Quinchao',             state: x)
Spree::County.find_or_create_by(name: 'Osorno',               state: x)
Spree::County.find_or_create_by(name: 'Puerto Octay',         state: x)
Spree::County.find_or_create_by(name: 'Purranque',            state: x)
Spree::County.find_or_create_by(name: 'Puyehue',              state: x)
Spree::County.find_or_create_by(name: 'Río Negro',            state: x)
Spree::County.find_or_create_by(name: 'San Juan de la Costa', state: x)
Spree::County.find_or_create_by(name: 'San Pablo',            state: x)
Spree::County.find_or_create_by(name: 'Chaitén',              state: x)
Spree::County.find_or_create_by(name: 'Futaleufú',            state: x)
Spree::County.find_or_create_by(name: 'Hualaihué',            state: x)
Spree::County.find_or_create_by(name: 'Palena',               state: x)
Spree::County.find_or_create_by(name: 'Coihaique',            state: xi)
Spree::County.find_or_create_by(name: 'Lago Verde',           state: xi)
Spree::County.find_or_create_by(name: 'Aisén',                state: xi)
Spree::County.find_or_create_by(name: 'Cisnes',               state: xi)
Spree::County.find_or_create_by(name: 'Guaitecas',            state: xi)
Spree::County.find_or_create_by(name: 'Cochrane',             state: xi)
Spree::County.find_or_create_by(name: 'O\'Higgins',           state: xi)
Spree::County.find_or_create_by(name: 'Tortel',               state: xi)
Spree::County.find_or_create_by(name: 'Chile Chico',          state: xi)
Spree::County.find_or_create_by(name: 'Río Ibáñez',           state: xi)
Spree::County.find_or_create_by(name: 'Punta Arenas',         state: xii)
Spree::County.find_or_create_by(name: 'Laguna Blanca',        state: xii)
Spree::County.find_or_create_by(name: 'Río Verde',            state: xii)
Spree::County.find_or_create_by(name: 'San Gregorio',         state: xii)
Spree::County.find_or_create_by(name: 'Cabo de Hornos',       state: xii)
Spree::County.find_or_create_by(name: 'Antártica',            state: xii)
Spree::County.find_or_create_by(name: 'Porvenir',             state: xii)
Spree::County.find_or_create_by(name: 'Primavera',            state: xii)
Spree::County.find_or_create_by(name: 'Timaukel',             state: xii)
Spree::County.find_or_create_by(name: 'Natales',              state: xii)
Spree::County.find_or_create_by(name: 'Torres del Paine',     state: xii)
Spree::County.find_or_create_by(name: 'Colina',               state: rm)
Spree::County.find_or_create_by(name: 'Lampa',                state: rm)
Spree::County.find_or_create_by(name: 'Tiltil',               state: rm)
Spree::County.find_or_create_by(name: 'Pirque',               state: rm)
Spree::County.find_or_create_by(name: 'Puente Alto',          state: rm)
Spree::County.find_or_create_by(name: 'San José de Maipo',    state: rm)
Spree::County.find_or_create_by(name: 'Buin',                 state: rm)
Spree::County.find_or_create_by(name: 'Calera de Tango',      state: rm)
Spree::County.find_or_create_by(name: 'Paine',                state: rm)
Spree::County.find_or_create_by(name: 'San Bernardo',         state: rm)
Spree::County.find_or_create_by(name: 'Alhué',                state: rm)
Spree::County.find_or_create_by(name: 'Curacaví',             state: rm)
Spree::County.find_or_create_by(name: 'María Pinto',          state: rm)
Spree::County.find_or_create_by(name: 'Melipilla',            state: rm)
Spree::County.find_or_create_by(name: 'San Pedro',            state: rm)
Spree::County.find_or_create_by(name: 'Cerrillos',            state: rm)
Spree::County.find_or_create_by(name: 'Cerro Navia',          state: rm)
Spree::County.find_or_create_by(name: 'Conchalí',             state: rm)
Spree::County.find_or_create_by(name: 'El Bosque',            state: rm)
Spree::County.find_or_create_by(name: 'Estación Central',     state: rm)
Spree::County.find_or_create_by(name: 'Huechuraba',           state: rm)
Spree::County.find_or_create_by(name: 'Independencia',        state: rm)
Spree::County.find_or_create_by(name: 'La Cisterna',          state: rm)
Spree::County.find_or_create_by(name: 'La Granja',            state: rm)
Spree::County.find_or_create_by(name: 'La Florida',           state: rm)
Spree::County.find_or_create_by(name: 'La Pintana',           state: rm)
Spree::County.find_or_create_by(name: 'La Reina',             state: rm)
Spree::County.find_or_create_by(name: 'Las Condes',           state: rm)
Spree::County.find_or_create_by(name: 'Lo Barnechea',         state: rm)
Spree::County.find_or_create_by(name: 'Lo Espejo',            state: rm)
Spree::County.find_or_create_by(name: 'Lo Prado',             state: rm)
Spree::County.find_or_create_by(name: 'Macul',                state: rm)
Spree::County.find_or_create_by(name: 'Maipú',                state: rm)
Spree::County.find_or_create_by(name: 'Ñuñoa',                state: rm)
Spree::County.find_or_create_by(name: 'Pedro Aguirre Cerda',  state: rm)
Spree::County.find_or_create_by(name: 'Peñalolén',            state: rm)
Spree::County.find_or_create_by(name: 'Providencia',          state: rm)
Spree::County.find_or_create_by(name: 'Pudahuel',             state: rm)
Spree::County.find_or_create_by(name: 'Quilicura',            state: rm)
Spree::County.find_or_create_by(name: 'Quinta Normal',        state: rm)
Spree::County.find_or_create_by(name: 'Recoleta',             state: rm)
Spree::County.find_or_create_by(name: 'Renca',                state: rm)
Spree::County.find_or_create_by(name: 'San Miguel',           state: rm)
Spree::County.find_or_create_by(name: 'San Joaquín',          state: rm)
Spree::County.find_or_create_by(name: 'San Ramón',            state: rm)
Spree::County.find_or_create_by(name: 'Santiago',             state: rm)
Spree::County.find_or_create_by(name: 'Vitacura',             state: rm)
Spree::County.find_or_create_by(name: 'El Monte',             state: rm)
Spree::County.find_or_create_by(name: 'Isla de Maipo',        state: rm)
Spree::County.find_or_create_by(name: 'Padre Hurtado',        state: rm)
Spree::County.find_or_create_by(name: 'Peñaflor',             state: rm)
Spree::County.find_or_create_by(name: 'Talagante',            state: rm)